import type { NextPage, GetStaticProps, InferGetStaticPropsType } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Banner from '../components/banner';
import Card from '../components/card';
import React from 'react';
import { fetchCafeterias } from '../lib/cafeterias_lib';

export interface ICafeterias {
  fsq_id: number;
  name: string;
  imgUrl?: string;
  website: string;
  address: string;
  zone: string;
}

//CLIENT
const Home: NextPage = (props: InferGetStaticPropsType<typeof getStaticProps>) => {

  const handleBannerClick = () => {
    alert('Ciao! Banner!')
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Café Conocedor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner buttonText='Cafeterias cerca de mi' handleOnClick={handleBannerClick} />
        <div className={styles.heroImage}>
          <Image alt='cafeteria hero image' src='/static/hero-img.png' width={700} height={400}/>
        </div>
        {props.cafeterias.length > 0 && 
        <React.Fragment>
        <h2 className={styles.heading2}>Cafeterias en Valencia</h2>
        <div className={styles.cardLayout}>
          {
            props.cafeterias.map((cafeteria: ICafeterias) => (
              <Card key={`${cafeteria.fsq_id}`} imgUrl={cafeteria.imgUrl || 'https://cdn.pixabay.com/photo/2016/04/12/11/19/coffee-1324126_960_720.jpg'} name={cafeteria.name} href={`/cafeteria/${cafeteria.fsq_id}`} />
            ))
          }
        </div>
        </React.Fragment>}
      </main>
    </div>
  );
};

// SERVER
export const getStaticProps: GetStaticProps = async () => {
  const cafeterias = await fetchCafeterias();

  return {
    props: {
      cafeterias
    },
  }
}

export default Home;
