import type { NextPage, GetStaticProps, InferGetStaticPropsType } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Banner from '../components/banner';
import Card from '../components/card';
import cafeterias from '../data/cafeterias.json';

export interface ICafeterias {
  id: number;
  name: string;
  imgUrl: string;
  website: string;
  address: string;
  zone: string;
}

const Home: NextPage = (props: InferGetStaticPropsType<typeof getStaticProps>) => {

  console.log(props);

  const handleBannerClick = () => {
    alert('Ciao! Banner!')
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Café Conocedor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner buttonText='Cafeterias cerca de mi' handleOnClick={handleBannerClick} />
        <div className={styles.heroImage}>
          <Image alt='cafeteria hero image' src='/static/hero-img.png' width={700} height={400}/>
        </div>
        <div className={styles.cardLayout}>
          {
            props.cafes.map((cafe: ICafeterias) => (
              <Card key={`${cafe.id}`} imgUrl={cafe.imgUrl} name={cafe.name} href={`/cafeteria/${cafe.id}`} />
            ))
          }
        </div>
      </main>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async (context) => {
  const cafes: ICafeterias[] = cafeterias
  return {
    props: {
      cafes
    },
  }
}

export default Home;
