import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Banner from '../components/banner';
import Card from '../components/card';


const Home: NextPage = () => {

  const handleBannerClick = () => {
    alert('Ciao! Banner!')
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Café Conocedor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner buttonText='Cafeterias cerca de mi' handleOnClick={handleBannerClick} />
        <div className={styles.heroImage}>
          <Image alt='cafeteria hero image' src='/static/hero-img.png' width={700} height={400}/>
        </div>
        <div className={styles.cardLayout}>
          <Card imgUrl={'/static/hero-img.png'} name={'LiaoCafe'} href={'/cafeteria/liao-cafe'} />
        </div>
      </main>
    </div>
  );
};

export default Home;
